#!/bin/csh -f

source /etc/profile.d/modules.csh

setenv MODULEPATH ${MODULEPATH}:/afs/@cell/common/usr/modules/@sys/modulefiles/TOK

module purge
module load anaconda/2/5.1

cd $HOME/python/tau
python ttevening.py
