#!/bin/csh -f

source /etc/profile.d/modules.csh

setenv GSLCONTRIB_LIB /afs/ipp/home/g/git/gsl_contrib/lib/libgsl-contrib.so
setenv LD_LIBRARY_PATH /afs/@cell/common/soft/gsl/2.1/amd64_sles11/gcc-4.8/lib 

setenv MODULEPATH ${MODULEPATH}:/afs/@cell/common/usr/modules/@sys/modulefiles/TOK

module purge
module load anaconda/2/5.1

cd $HOME/python/tau
python ttevening.py
