#!/bin/csh -f

setenv osy `fs sysname | awk -F\' '{print $2}'`

if ($osy == 'amd64_sles11' || $osy == 'amd64_linux26') then

   source /etc/profile.d/modules.csh
   module purge
   if ($osy == 'amd64_sles11') then
      module load anaconda/2_4.1.1
   else
      module load anaconda/2_4.2.0
   endif
else

  alias python /usr/ads/diags/python2.7/bin/python2.7

endif

cd $HOME/python/tau
python toth_gui.py
